version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:3306
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql
  kafka:
    image: johnnypark/kafka-zookeeper:2.6.0
    ports:
      - 2181:2181
    environment:
      ADVERTISED_HOST: 127.0.0.1
      NUM_PARTITIONS: 10

volumes:
  mariadb:
